spring:
  profiles:
    active:
      - local
    group:
      local:
        - oauth
        - db-local
        - cloud
        - redis
        - chatbot
      dev:
        - oauth
        - db-dev
        - cloud
        - redis
        - chatbot
    include: oauth, db, cloud, redis, chatbot
