spring:
  profiles:
    active:
      - local
    group:
      local:
        - oauth
        - db-local
        - cloud
        - redis
        - rabbitmq-local
      dev:
        - oauth
        - db-dev
        - cloud
        - redis
        - rabbitmq-dev
    include: oauth, db, cloud, redis, rabbitmq
  
