spring:
  config:
    activate:
      on-profile: "fcm"

firebase:
  project-id: ${FIREBASE_PROJECT_ID}
  private-key: ${FIREBASE_PRIVATE_KEY}
  client-email: ${FIREBASE_CLIENT_EMAIL}
  private-key-id: ${FIREBASE_PRIVATE_KEY_ID}
  client-id: ${FIREBASE_CLIENT_ID}
