spring:
  profiles:
    active:
      - local
    group:
      local:
        - oauth
        - db-local
        - cloud
        - redis
        - rabbitmq-local
        - fcm
      dev:
        - oauth
        - db-dev
        - cloud
        - redis
        - rabbitmq-dev
        - fcm
    include: oauth, db, cloud, redis, rabbitmq, fcm

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.conkiri: DEBUG
